// packages/create-vite-plugin-web-extension/template/framework/svelte/src/entries/options/App.svelte
<script>
import PageContent from "~/lib/PageContent.svelte";
</script>

<main>
  <PageContent> Options </PageContent>
</main>

<style>
main {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}
</style>

// packages/create-vite-plugin-web-extension/template/framework/vue-ts/src/entries/options/App.vue
<template>
  <main>
    <PageContent> Options </PageContent>
  </main>
</template>

<script setup lang="ts">
import PageContent from "~/components/PageContent.vue";
</script>

<style>
main {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}
</style>
