// packages/create-vite-plugin-web-extension/template/framework/svelte-ts/src/lib/PageContent.svelte
<script lang="ts">
  import logo from "~/assets/logo.svg";

  const imageUrl = new URL(logo, import.meta.url).href;

  let count: number = 0
  const increment = () => {
    count += 1
  }
</script>

<img src={imageUrl} height="45" alt="" />
<h1>
  <slot></slot>
</h1>
<button type="button" on:click={increment}>
  Clicks: {count}
</button>

<style>
  h1 {
    margin: 5px;
  }
  
  button {
    margin-top: 10px;
  }
</style>

// packages/create-vite-plugin-web-extension/template/framework/react/src/components/PageContent.jsx
import { useState } from "react";
import "./PageContent.css";
import logo from "~/assets/logo.svg";

function PageContent(props) {
  const imageUrl = new URL(logo, import.meta.url).href;

  const [count, setCount] = useState(0);

  return (
    <div>
      <img src={imageUrl} height="45" alt="" />
      <h1>{props.children}</h1>
      <button type="button" onClick={() => setCount((count) => count + 1)}>
        Count: {count}
      </button>
    </div>
  );
}

export default PageContent;
